package main
 
import (
    "fmt"
    "os"
)
 
func Foo() error {
    var err *os.PathError = nil
    return err
}
 
func main() {
    err := Foo()
    fmt.Println(err)
    fmt.Println(err == nil)
}

Программа выведет на экран <nil> false

Такое поведение обусловлено тем, что интерфейс хранит в себе тип, который его реализует, и значение типа. В данном случае *os.PathError != nil.
